mqtt:
  config:
    username: admin
    password: 4sp3Gms8
    #MQTT-服务器连接地址，如果有多个，用逗号隔开，如：tcp://xxx.xxx.xx.xxx:1883,tcp://xxx.xxx.xxx.xxx:1883
    hostUrl: tcp://iotx-rabbitmq:1883
    #两个客户端的clientId不能相同，生产者和消费者的clientId不能相同
    #    pubClientId: pub-client-id-al68pq1w-dev
    #    subClientId: sub-client-id-9v83pp7c-dev
    clientId: ${random.value}
    #发布的主题--MQTT-默认的消息推送主题，实际可在调用接口时指定
    # 当topic不固定，可以不配置
    #    pubTopic: pubTopic
    pubTopic: pubTopic
    #订阅的主题
    # 推荐用模糊匹配的方式订阅topic
    #    subTopic: subTopic,oil-topic,broadcast-topic,fault-topic
    subTopic: subTopic,topic/devices/upload,topic/devices/rpc/reply/+,/2001/+/up
    completionTimeout: 3000

# mybaits-plus配置--放在这里才能识别，因为不属于org.springframework.boot体系下
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: 0
      field-strategy: 1
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true

# 只有groupid为org.springframework.boot的才能识别
spring:
  profiles:
    # 运行模式：默认dev
    active: dev
  # redis 配置
  redis:
    # 服务器地址
    host: iotx-redis
    # 默认端口6379
    port: 6379
    # 密码，默认为空
    password: zhb123!@#
    # 超时时间
    timeout: 5000
    # Redis数据库索引（默认为0）
    database: 0
    # 连接池配置
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
